// SPDX-License-Identifier: MIT
pragma solidity ^0.8.26;

import "@openzeppelin/contracts/token/ERC721/extensions/ERC721URIStorage.sol";
import "@openzeppelin/contracts/access/Ownable.sol";

/**
 * @title SovereignMatterRegistry
  * @notice ERC721 "material passport" registry for EV-battery minerals (cobalt, nickel, lithium, manganese, graphite).
   *         Each token represents a unique mineral batch and can store:
    *         - human/machine-readable batch details
     *         - linked third-party audit report URIs
      *         - on-chain auditor attestations
       *         - certification presence flags
        *         - derived compliance + non-compliance flag status
         *
          * @dev Design notes (OpenZeppelin Contracts v5):
           *      - Uses ERC721URIStorage for optional per-token metadata URIs.
            *      - Ownable uses Ownable(msg.sender) in the constructor.
             *      - OZ v5 removed the _exists() helper; token existence is checked via _ownerOf(tokenId) != address(0).
              *      - Transfer hooks changed: compliance enforcement is implemented by overriding {_update}.
               *        Compliance checks are applied ONLY to transfers (from != 0 and to != 0), not to minting or burning.
                *
                 *      Compliance model:
                  *      - A token is considered compliant if all required certifications are present AND at least one attestation exists.
                   *      - Non-compliant tokens are flagged and cannot be transferred.
                    */
                    contract SovereignMatterRegistry is ERC721URIStorage, Ownable {
                        /// @dev Monotonically increasing counter used to assign new tokenIds.
                            uint256 private _tokenIdCounter;

                                enum MineralType {
                                        Cobalt,
                                                Nickel,
                                                        Lithium,
                                                                Manganese,
                                                                        Graphite
                                                                            }

                                                                                struct MineralBatch {
                                                                                        MineralType mineralType;
                                                                                                string batchDetails;
                                                                                                        bool compliant;
                                                                                                                bool flagged;
                                                                                                                    }
                                                                                                                    
                                                                                                                        struct AuditReport {
                                                                                                                                string uri;
                                                                                                                                        uint256 timestamp;
                                                                                                                                            }
                                                                                                                                            
                                                                                                                                                struct Attestation {
                                                                                                                                                        address auditor;
                                                                                                                                                                string details;
                                                                                                                                                                        uint256 timestamp;
                                                                                                                                                                            }
                                                                                                                                                                            
                                                                                                                                                                                mapping(uint256 => MineralBatch) private _mineralBatches;
                                                                                                                                                                                    mapping(uint256 => AuditReport[]) private _auditReports;
                                                                                                                                                                                        mapping(uint256 => Attestation[]) private _attestations;
                                                                                                                                                                                            mapping(address => bool) private _authorizedAuditors;
                                                                                                                                                                                                mapping(uint256 => mapping(string => bool)) private _certifications;
                                                                                                                                                                                                
                                                                                                                                                                                                    event MineralBatchMinted(uint256 indexed tokenId, address indexed owner, MineralType mineralType, string batchDetails);
                                                                                                                                                                                                        event MineralBatchUpdated(uint256 indexed tokenId, string batchDetails);
                                                                                                                                                                                                            event CertificationUpdated(uint256 indexed tokenId, string certification, bool present);
                                                                                                                                                                                                                event AuditReportLinked(uint256 indexed tokenId, string uri, uint256 timestamp);
                                                                                                                                                                                                                    event AttestationSubmitted(uint256 indexed tokenId, address indexed auditor, string details, uint256 timestamp);
                                                                                                                                                                                                                        event ComplianceFlagUpdated(uint256 indexed tokenId, bool flagged);
                                                                                                                                                                                                                            event MineralBatchTransferred(address indexed from, address indexed to, uint256 indexed tokenId);
                                                                                                                                                                                                                                event AuditorAuthorized(address indexed auditor, bool authorized);
                                                                                                                                                                                                                                
                                                                                                                                                                                                                                    modifier tokenExists(uint256 tokenId) {
                                                                                                                                                                                                                                            require(_ownerOf(tokenId) != address(0), "Token does not exist");
                                                                                                                                                                                                                                                    _;
                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                            modifier onlyAuthorizedAuditor() {
                                                                                                                                                                                                                                                                    require(_authorizedAuditors[msg.sender], "Not an authorized auditor");
                                                                                                                                                                                                                                                                            _;
                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                    constructoOwnable(msg.sender) {}
                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                        function mintMineralBatch(
                                                                                                                                                                                                                                                                                                address to,
                                                                                                                                                                                                                                                                                                        MineralType mineralType,
                                                                                                                                                                                                                                                                                                                string calldata batchDetails,
                                                                                                                                                                                                                                                                                                                        string calldata tokenURI_,
                                                                                                                                                                                                                                                                                                                                string[] calldata certifications
                                                                                                                                                                                                                                                                                                                                    ) external onlyOwner returns (uint256) {
                                                                                                                                                                                                                                                                                                                                            _tokenIdCounter++;
                                                                                                                                                                                                                                                                                                                                                    uint256 newTokenId = _tokenIdCounter;
                                                                                                                                                                                                                                                                                                                                                            _safeMint(to, newTokenId);
                                                                                                                                                                                                                                                                                                                                                                    if (bytes(tokenURI_).length > 0) {
                                                                                                                                                                                                                                                                                                                                                                                _setTokenURI(newTokenId, tokenURI_);
                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                _mineralBatches[newTokenId] = MineralBatch({
                                                                                                                                                                                                                                                                                                                                                                                                            mineralType: mineralType,
                                                                                                                                                                                                                                                                                                                                                                                                                        batchDetails: batchDetails,
                                                                                                                                                                                                                                                                                                                                                                                                                                    compliant: false,
                                                                                                                                                                                                                                                                                                                                                                                                                                                flagged: false
                                                                                                                                                                                                                                                                                                                                                                                                                                                        });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                for (uint256 i = 0; i < certifications.length; i++) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            _certifications[newTokenId][certifications[i]] = true;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        emit CertificationUpdated(newTokenId, certifications[i], true);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        _updateComplianceStatus(newTokenId);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                emit MineralBatchMinted(newTokenId, to, mineralType, batchDetails);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return newTokenId;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                function updateMineralBatch(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        uint256 tokenId,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                string calldata newBatchDetails,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        string calldata newTokenURI,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                string[] calldata certifications
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ) external tokenExists(tokenId) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            address owner_ = ownerOf(tokenId);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    require(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                msg.sender == owner_ || isApprovedForAll(owner_, msg.sender) || getApproved(tokenId) == msg.sender,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "Not authorized to update"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            _mineralBatches[tokenId].batchDetails = newBatchDetails;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (bytes(newTokenURI).length > 0) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                _setTokenURI(tokenId, newTokenURI);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                for (uint256 i = 0; i < certifications.length; i++) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            _certifications[tokenId][certifications[i]] = true;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        emit CertificationUpdated(tokenId, certifications[i], true);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        _updateComplianceStatus(tokenId);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                emit MineralBatchUpdated(tokenId, newBatchDetails);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        function linkAuditReport(uint256 tokenId, string calldata uri) external tokenExists(tokenId) onlyOwner {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                AuditReport memory report = AuditReport({uri: uri, timestamp: block.timestamp});
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        _auditReports[tokenId].push(report);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                emit AuditReportLinked(tokenId, uri, block.timestamp);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        _updateComplianceStatus(tokenId);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                function submitAttestation(uint256 tokenId, string calldata details)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        external
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                tokenExists(tokenId)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        onlyAuthorizedAuditor
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Attestation memory attestation = Attestation({auditor: msg.sender, details: details, timestamp: block.timestamp});
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            _attestations[tokenId].push(attestation);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    emit AttestationSubmitted(tokenId, msg.sender, details, block.timestamp);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            _updateComplianceStatus(tokenId);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    function setAuditorAuthorization(address auditor, bool authorized) 
